name             'aws-example'
maintainer       'Brian Drust'
maintainer_email 'bdrusty@gmail.com'
license          'All rights reserved'
description      'example of a simple AWS web app'
version          '1.0.0'